### ISSUE TITLE
Issue Getting Delta5 to work

### ISSUE THREAD

**Issue by blakermchale** [scottgchin/delta5_race_timer#90]
I've been trying to get the app to run by following the Software Setup Guide, but when in the settings this error keeps occurring.
This only happens in the settings, and I'm unable to add pilots or heats.
None of python files were changed after cloning

Any help would be appreciated.
Thanks.

```
Client connected
connect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 423, in _trigger_event
    return self.handlers[event](*args)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 503, in _handle_eio_connect
    return self._handle_connect(sid, '/')
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 421, in _handle_connect
    self.environ[sid]) is False:
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 490, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 251, in _handler
    *args)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 632, in _handle_event
    ret = handler()
  File "server.py", line 339, in connect_handler
    emit_leaderboard() # Race page, load leaderboard for current laps
  File "server.py", line 835, in emit_leaderboard
    heat_id=RACE.current_heat, node_index=node).first().pilot_id
AttributeError: 'NoneType' object has no attribute 'pilot_id'

```

**Comment by floriangaller** [comment]
Hello,

I can confim that I have the same issue: I started with a clean install of raspbian strech Version: November 2018 Release date: 2018-11-13 and installed Delta 5 according to the instructions :"Hardware and Software Setup Instructions". I also tried different browsers: Firefox, Chrome still the same issue. I'm also unable to shut down the raspi by the gui buttons. Furthermore, all the calibration values fields are empty. The connection to the arduinos seems to work fine... (when i connect them they get shown in the setting tab. However, it is not possible to assign frequencies.) 
Also the timingserver used for the connection to Livetime doesn't work.

If anybody can offer help it would be highly appreciated

Thanks

**Comment by scottgchin** [comment]
Did you notice any errors during the requirements.txt install portion?  If you're looking for an easier method, there is an sd card image file made from my install on the pinned post of the facebook post.  Just write it to your sd card, and it should have everything configured.  Just a note my sd card was a 32gb card.

**Comment by floriangaller** [comment]
I didn't noticed any errory during the install of requirements.txt and if i ran this command again it wirtes out that everything is installed... I have no facebook account and, therfore, i will try now the image from https://github.com/spuder/pi-gen

**Comment by martinglass** [comment]
> Did you notice any errors during the requirements.txt install portion? If you're looking for an easier method, there is an sd card image file made from my install on the pinned post of the facebook post. Just write it to your sd card, and it should have everything configured. Just a note my sd card was a 32gb card.

Hi Scott, I'm getting similar issues. 

I've got it working now. Not quite sure how, but here are some of the steps
I downgraded from the  RPi 3 Model B+ to the standard RPi 3 Model B and started again. I followed all the instructions and everything went well without errors. But the web server still wouldn't serve.

I then removed the whole delta5_race_timer directory 
rm -r ~/delta5_race_timer
... and reinstalled it 
cd ~
git clone https://github.com/scottgchin/delta5_race_timer.git
cd /home/pi/delta5_race_timer/src
sudo chmod 777 delta5server
sudo reboot

After the reboot, it all sprung to life.

I'm not sure what went wrong, but I think the database got corrupted in the first install and the second re-install started with a clean one. 

Maybe, I'm missing the mark, but anyway, in case it's any use to anyone else, this worked for me (after a lot of trial and error).
